version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.gitlab.com/dev8/api-resize-images
    container_name: api-resize-image
    restart: unless-stopped
    ports:
      - "8383:8383"
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8383/ || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
